DROP TABLE CALENDARIO CASCADE CONSTRAINTS;
DROP TABLE JUNTA CASCADE CONSTRAINTS;
DROP TABLE SOCIOS CASCADE CONSTRAINTS;
DROP TABLE CUOTAS CASCADE CONSTRAINTS;
DROP TABLE ACTIVIDADES CASCADE CONSTRAINTS;
DROP TABLE ACTIVIDADES_SOCIOS CASCADE CONSTRAINTS;

CREATE TABLE CALENDARIO(
    CALENDARIO_ID NUMBER PRIMARY KEY,
    ANYO DATE
);

CREATE TABLE JUNTA(
    FECHA_INI DATE UNIQUE NOT NULL,
    FECHA_FIN DATE UNIQUE NOT NULL,
    IMFORMACION VARCHAR2(128),     
    CONSTRAINT JUNTA_PK PRIMARY KEY(FECHA_INI,FECHA_FIN)
);

CREATE TABLE SOCIOS (
    COD_SOC NUMBER(9) PRIMARY KEY,
    NOMBRE VARCHAR2(24) NOT NULL,
    APELLIDOS VARCHAR2(24) NOT NULL,
    DNI VARCHAR2(9),
    FECHA_ALTA  DATE NOT NULL,
    TELEFONO NUMBER(12),
    EMAIL VARCHAR2(24),
    FECHA_NACI DATE NOT NULL,
    TIPO_SOCIO VARCHAR2(24) NOT NULL CONSTRAINT TIPO_CK CHECK (TIPO_SOCIO = 'USUARIO' OR TIPO_SOCIO = 'ADMINISTRADOR'),
    CARGO VARCHAR2(24) CONSTRAINT CARGO_CK CHECK (CARGO = 'PRESIDENTE' OR CARGO = 'VICEPRESIDENTE' OR CARGO = 'SECRETARIO' OR CARGO = 'TESORERO' OR CARGO = 'VOCAL'),
    FECHA_INICIO DATE,
    FECHA_FINAL DATE
);

CREATE TABLE CUOTAS(
    TIPO_CUOTA VARCHAR2(24) PRIMARY KEY CONSTRAINT TIPO_CUOTA_CK CHECK (TIPO_CUOTA = 'MENORES' OR TIPO_CUOTA= 'ADULTOS' OR TIPO_CUOTA= 'ADMINISTRADOR'),
    IMPORTE VARCHAR2(24) NOT NULL,
    ANYO_VALIDEZ DATE NOT NULL,
    IMPORTE_PAGO NUMBER(24) ,
    SOCIOS_COD_SOC NUMBER(9) NOT NULL CONSTRAINT SOC_COD_FK REFERENCES SOCIOS(COD_SOC)
);

CREATE TABLE ACTIVIDADES(
    COD_ACTIVI VARCHAR2(24) PRIMARY KEY,
    TIPO VARCHAR2(24) NOT NULL CONSTRAINT TIPO_ACTIVIDADES_CK CHECK (TIPO = 'SALIDA_AL_MONTE' OR TIPO = 'ALBERFGUE_FIN_DE_SEMANA' OR TIPO = 'REUNION' OR TIPO = 'COMIDA' OR TIPO = 'OTROS'),
    DIFICULTAD  VARCHAR(24) NOT NULL CONSTRAINT DIFICULTAD_CK CHECK (DIFICULTAD = 'ALTA' OR DIFICULTAD = 'MEDIA' OR DIFICULTAD = 'BAJA'),
    SOCIOS_COD_SOC NUMBER(9) NOT NULL CONSTRAINT SOC_ACTIVI_FK REFERENCES SOCIOS(COD_SOC),
    PRECIO NUMBER NOT NULL,
    MOTIVO_SUSPENSION VARCHAR2(200),
    CALENDARIO_FK NUMBER CONSTRAINT CALEND_ID_FK REFERENCES CALENDARIO(CALENDARIO_ID),
    COD_SOCIOS NUMBER(9)
);

CREATE TABLE ACTIVIDADES_SOCIOS(
    SOCIOS_COD_SOC NUMBER(9) CONSTRAINT SOCIOS_FK REFERENCES SOCIOS(COD_SOC),
    ACTIVIDADES_COD_ACTIVI VARCHAR2(8) CONSTRAINT ACTIVIDADES_FK REFERENCES ACTIVIDADES(COD_ACTIVI), 
    CONSTRAINT ACTIVIDADES_SOCIOS_PK PRIMARY KEY(SOCIOS_COD_SOC,ACTIVIDADES_COD_ACTIVI)
);

ALTER TABLE SOCIOS ADD CONSTRAINT JUNTA_SOCIS_FK FOREIGN KEY(FECHA_INICIO,FECHA_FINAL) REFERENCES JUNTA(FECHA_INI,FECHA_FIN);
ALTER TABLE SOCIOS ADD CONSTRAINT SOCIOS_SOC_RESP_FK FOREIGN KEY (COD_SOCIO_RESPONSABLE) REFERENCES SOCIOS (COD_SOC);
ALTER TABLE ACTIVIDADES ADD CONSTRAINT ACTIVIADES_SOCIOS_FK FOREIGN KEY(COD_SOCIOS) REFERENCES SOCIOS(COD_SOC);


---------------------------------------------------- TRIGGERS---------------------------------------

-- LO PRIMERO QUE VOY HACER ES UNA TABLA DE CONTROL, PARA QUE ME SALGAN LOS ERRORES:
DROP TABLE TABLA_CONTROL;

CREATE TABLE TABLA_CONTROL(
COD_SOCIO NUMBER(9,0),
NOMBRE VARCHAR2(24),
APELLIDOS VARCHAR2(24),
FECHA_INCIDENCIA DATE DEFAULT SYSDATE,
TEXTO VARCHAR2(300));

-- VOY AÑADIR UN CAMPO NUEVO DE "COD_SOCIO_RESPONSABLE":

ALTER TABLE SOCIOS ADD COD_SOCIO_RESPONSABLE NUMBER (9,0);

-- HAGO UN TRIGGER PARA CONTROLAR LA EDAD DE LOS USUARIOS QUE QUIEREN REGISTRARSE COMO SOCIOS:

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER VALIDAR_SOCIO
BEFORE INSERT ON SOCIOS
FOR EACH ROW

DECLARE
    V_AÑOS_USUARIO_NUEVO NUMBER; -- AQUI SACO LOS AÑOS DEL USUARIO QUE QUIERE REGISTRARSE, RESTANDO LA FECHA ACTUAL MENOS SU FECHA CUMPLEAÑOS
    V_AÑOS_RESPONSABLE NUMBER; --> AÑOS DEL SOCIO RESPONSABLE

    
BEGIN

    --> METER COLUMNA NUEVA DE "SOCIO_TUTOR" O "COD_SOCIO_RESPONSABLE" EN LA TABALA SOCIOS, QUE ES QUE SE VA A RESPONSABILIZAR DEL MENOR
    
    
    SELECT TRUNC((SYSDATE-:NEW.FECHA_NACI)/365,0) INTO V_AÑOS_USUARIO_NUEVO FROM DUAL; --> "DUAL" --> TABLA TEMPORAL --> AÑOS DEL NUEVO SOCIO

    --> COMPROBAR QUE EL SOCIO NUEVO TIENE MENOS DE 4 AÑOS
    
    IF V_AÑOS_USUARIO_NUEVO<4 THEN
    RAISE_APPLICATION_ERROR(-20500, 'EL USUARIO TIENE MENOS DE 4 AÑOS');
    INSERT INTO TABLA_CONTROL (TEXTO) VALUES ('EL USUARIO TIENE MENOS DE 4 AÑOS');
    
    END IF;
    
    --> SI EL USUARIO TIENE MAS DE 4 AÑOS Y NO TIENE SOCIO RESPONSABLE (NULL) O ES MENOR DE 18 AÑOS
    
    IF V_AÑOS_USUARIO_NUEVO<18 AND V_AÑOS_RESPONSABLE IS NOT NULL THEN
    RAISE_APPLICATION_ERROR(-20800,'FIGURA... NO EXISTE RESPONSABLE');
    INSERT INTO TABLA_CONTROL (TEXTO) VALUES ('FIGURA... NO EXISTE RESPONSABLE');
    END IF;
    
    IF V_AÑOS_USUARIO_NUEVO<18 AND V_AÑOS_RESPONSABLE>18 THEN
    SELECT TRUNC((SYSDATE-FECHA_NACI)/365,0) INTO V_AÑOS_RESPONSABLE FROM SOCIOS WHERE COD_SOCIO_RESPONSABLE=(SELECT COD_SOC FROM SOCIOS);
    END IF;
    

    IF V_AÑOS_RESPONSABLE<18 THEN

    RAISE_APPLICATION_ERROR(-20100, 'EL USUARIO TIENE QUE TENER UN SOCIO RESPONSABLE MAYOR DE 18 AÑOS');
    INSERT INTO TABLA_CONTROL (TEXTO) VALUES ('EL USUARIO TIENE QUE TENER UN SOCIO RESPONSABLE MAYOR DE 18 AÑOS');

    END IF;
    
    
END VALIDAR_SOCIO;    

SHOW ERRORS;

--AÑADO 6 SOCIOS (

INSERT INTO SOCIOS VALUES(1,'PACO','RUIZ','12345789',sysdate,623586975,'PRUIZ@GMAIL.COM','10/05/1971','USUARIO',NULL,NULL,NULL,NULL); --> ALUMNO RESPONSABLE MAYOR DE 18
INSERT INTO SOCIOS VALUES(2,'FERNANDO','LOPEZ',NULL,'10/05/2019',NULL,NULL,'10/05/2018','USUARIO',NULL,NULL,NULL,1); --> USUARIO MENOR DE 4 AÑOS
INSERT INTO SOCIOS VALUES(3,'ION','PEREZ',NULL,'10/05/2012',NULL,NULL,'10/05/2007','USUARIO',NULL,NULL,NULL,NULL); --> ENTRE 4 Y 18 AÑOS CON SOCIO RESPONSABLE MAYOR DE 18 AÑOS
INSERT INTO SOCIOS VALUES(4,'LUIS','MENDEZ',NULL,'10/05/2010',NULL,NULL,'10/05/2006','USUARIO',NULL,NULL,NULL,2); --> MENOR DE 18 AÑOS CON RESPONSABLE MAYOR DE 18 AÑOS
INSERT INTO SOCIOS VALUES(5,'ALFONSO','GONZALEZ',NULL,'10/05/2017',NULL,NULL,'10/05/2010','USUARIO',NULL,NULL,NULL,4); --> LE DIGO QUE SU SOCIO RESPONSABLE TIENE MENOS DE 18 AÑOS, QUE ES EL SOCIO NUMERO 4
INSERT INTO SOCIOS VALUES(6,'LEONARDO','SAGUNTO',NULL,'10/05/2019',NULL,NULL,'10/05/2018','USUARIO',NULL,NULL,NULL,NULL);
INSERT INTO SOCIOS VALUES(7,'FERNANDO','LOPEZ',NULL,'10/05/2017',NULL,NULL,'10/05/2013','USUARIO',NULL,NULL,NULL,1);
INSERT INTO SOCIOS VALUES(9,'PEPE','ARIAS',NULL,'17/02/2010',NULL,NULL,'10/09/1971','USUARIO',NULL,NULL,NULL,NULL);
    
    
    

