CREATE TABLE CALENDARIO(
    CALENDARIO_ID NUMBER PRIMARY KEY,
    ANYO DATE
);

CREATE TABLE JUNTA(
    FECHA_INI DATE UNIQUE NOT NULL,
    FECHA_FIN DATE UNIQUE NOT NULL,
    IMFORMACION VARCHAR2(128), 
    
    CONSTRAINT JUNTA_PK PRIMARY KEY(FECHA_INI,FECHA_FIN)
);

CREATE TABLE SOCIOS (
    COD_SOC NUMBER(6) PRIMARY KEY,
    NOMBRE VARCHAR2(24) NOT NULL,
    APELLIDOS VARCHAR2(24) NOT NULL,
    DNI VARCHAR2(9),
    FECHA_ALTA  SYSDATE NOT NULL,
    TELEFONO NUMBER(12),
    EMAIL VARCHAR2(24),
    ADULTO BOOLEAN NOT NULL,
    TIPO_SOCIO VARCHAR2(24) NOT NULL,
    CARGO VARCHAR2(24)

    CONSTRAINT TIPO_CK CHECK (TIPO_SOCIO = 'USUARIO' OR TIPO_SOCIO = 'ADMINISTRADOR'),
    CONSTRAINT TIPO_CK CHECK (CARGO = 'PRESIDENTE' OR CARGO = 'VICEPRESIDENTE' OR CARGO = 'SECRETARIO' OR CARGO = 'TESORERO' OR CARGO = 'VOCAL')
);

CREATE TABLE CUOTAS(
    TIPO_CUOTA VARCHAR2(24) PRIMARY KEY,
    IMPORTE VARCHAR2(24) NOT NULL,
    ANYO_VALIDEZ DATE NOT NULL,
    PAGO BOOLEAN,
    SOCIOS_COD_SOC VARCHAR2(24) NOT NULL CONSTRAINT SOC_COD_FK REFERENCES SOCIOS(COD_SOC)
    
    CONSTRAINT TIPO_CUOTA_CK CHECK (TIPO_CUOTA = 'MENORES' OR TIPO_CUOTA= 'ADULTOS' OR TIPO_CUOTA= 'ADMINISTRADOR')
);

CREATE TABLE ACTIVIDADES(
    COD_ACTIVI VARCHAR2(24) PRIMARY KEY,
    TIPO VARCHAR2(24) NOT NULL,
    DIFICULTAD  VARCHAR(24) NOT NULL,
    SOCIOS_COD_SOC VARCHAR2(24) NOT NULL CONSTRAINT SOC_COD_FK REFERENCES SOCIOS(COD_SOC),
    PRECIO NUMBER NOT NULL,
    MOTIVO_SUSPENSION VARCHAR2(200),
    CALENDARIO_FK NUMBER CONSTRAINT CALEND_ID_FK REFERENCES CALENDARIO(CALENDARIOI_ID)
    
    CONSTRAINT TIPO_CK CHECK (TIPO = 'SALIDA_AL_MONTE' OR TIPO = 'ALBERFGUE_FIN_DE_SEMANA' OR TIPO = 'REUNION' OR TIPO = 'COMIDA' OR TIPO = 'OTROS'),
    CONSTRAINT DIFICULTAD_CK CHECK (DIFICULTAD = 'ALTA' OR DIFICULTAD = 'MEDIA' OR DIFICULTAD = 'BAJA')
);

